---
- name: Generate Proxy PAC files
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Create output file
      file:
        state: directory
        dest: "{{ playbook_dir }}/output"

    - name: Return hosts from Mullvad.net
      uri:
        url: https://api.mullvad.net/app/v1/relays
        method: GET
        body_format: json
      register: hosts_curl

    - name: Set fact to convert hosts to pretty JSON
      set_fact:
        hosts_json: "{{ hosts_curl.json | json_query('wireguard.relays[].hostname') }}"

    - name: Create templates
      template:
        src: "{{ item }}.pac.j2"
        dest: "{{ playbook_dir }}/output/{{ item }}.pac"
      loop:
        - proxy
        - random
