---
proxies:
  - location: Sweden
    tld: se
    relays:
      - 1
      - 3
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 12
      - 13
      - 14
      - 15
      - 17
      - 18
      - 19
      - 21
      - 22
      - 23
      - 24

  - location: UK
    tld: co.uk
    hostname: gb
    relays:
      - 31
      - 32
